import {act,renderHook,waitFor} from '@testing-library/react-native';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import type {PropsWithChildren} from 'react';
import {usePaymentMethods,useSavePaymentMethod,useSavePaymentTransfer,useCorrectMethodBalance} from '../../src/hooks/usePaymentMethods';
import {usePreferencesStore} from '../../src/stores/usePreferencesStore';
const mockRpc=jest.fn();
jest.mock('../../src/lib/supabase',()=>({supabase:{rpc:(...args:any[])=>({abortSignal:(signal:AbortSignal)=>mockRpc(...args,signal)})}}));
const profile={user_id:'owner',timezone:'Asia/Manila'} as any;
const input={id:'id',method:'card' as const,paymentType:'Debit card',name:' Metrobank ',lastFour:'',openingBalance:'40300.5',operation:'create' as const};
function setup(){const client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:Infinity},mutations:{retry:false,gcTime:Infinity}}});const invalidate=jest.spyOn(client,'invalidateQueries');function Wrapper({children}:PropsWithChildren){return <QueryClientProvider client={client}>{children}</QueryClientProvider>;}return {client,invalidate,...renderHook(()=>({methods:usePaymentMethods(),save:useSavePaymentMethod(),transfer:useSavePaymentTransfer(),correct:useCorrectMethodBalance()}),{wrapper:Wrapper})};}
beforeEach(()=>{mockRpc.mockReset();usePreferencesStore.setState({profile});mockRpc.mockImplementation((name:string)=>Promise.resolve({error:null,data:name==='payment_method_snapshot'?{owner:'owner',timezone:'Asia/Manila',methods:[],transfers:[],corrections:[]}:{id:'id',user_id:'owner'}}));});
afterEach(()=>usePreferencesStore.setState({profile:null}));
test('canonical balance is saved separately with optional digits null and refreshes methods',async()=>{const h=setup();await act(async()=>{await h.result.current.save.mutateAsync(input);});expect(mockRpc).toHaveBeenCalledWith('save_payment_method',{p_method:expect.objectContaining({name:'Metrobank',openingBalance:'40300.50',lastFour:null})},expect.any(AbortSignal));expect(h.invalidate).toHaveBeenCalledWith({queryKey:['paymentMethods']});h.unmount();h.client.clear();});
test('missing initial balance never reaches the server',async()=>{const h=setup();await act(async()=>{await expect(h.result.current.save.mutateAsync({...input,openingBalance:''})).rejects.toThrow('initial balance');});expect(mockRpc.mock.calls.some(c=>c[0]==='save_payment_method')).toBe(false);h.unmount();h.client.clear();});
test('failed method save does not invalidate balances or invoke a transaction save',async()=>{const h=setup();mockRpc.mockImplementation(name=>Promise.resolve(name==='save_payment_method'?{data:null,error:{code:'500'}}:{error:null,data:{owner:'owner',timezone:'Asia/Manila',methods:[]}}));await act(async()=>{await expect(h.result.current.save.mutateAsync(input)).rejects.toThrow('draft');});expect(h.invalidate).not.toHaveBeenCalled();expect(mockRpc.mock.calls.some(c=>c[0]==='save_transaction')).toBe(false);h.unmount();h.client.clear();});
test('snapshot from a different owner is never exposed',async()=>{mockRpc.mockResolvedValue({error:null,data:{owner:'other',timezone:'Asia/Manila',methods:[{id:'private'}],transfers:[],corrections:[]}});const h=setup();await waitFor(()=>expect(h.result.current.methods.isSuccess).toBe(true));expect(h.result.current.methods.methods).toBeUndefined();h.unmount();h.client.clear();});
test('transfers invalidate method balances without invalidating budgets',async()=>{const h=setup();await act(async()=>{await h.result.current.transfer.mutateAsync({id:'id',operation:'create',sourceId:'cash',destinationId:'card',amount:'25.5',date:'2026-10-08'});});expect(mockRpc).toHaveBeenCalledWith('save_payment_transfer',{p_transfer:expect.objectContaining({amount:'25.50'})},expect.any(AbortSignal));expect(h.invalidate.mock.calls.map(c=>c[0])).toEqual([{queryKey:['reports']},{queryKey:['reportTransfers']},{queryKey:['reportTransactions']},{queryKey:['paymentMethods']} ]);h.unmount();h.client.clear();});
test('stale balance correction supplies a recovery message and preserves caches',async()=>{const h=setup();mockRpc.mockImplementation(name=>Promise.resolve(name==='correct_method_balance'?{data:null,error:{code:'40001'}}:{error:null,data:{owner:'owner',timezone:'Asia/Manila',methods:[]}}));await act(async()=>{await expect(h.result.current.correct.mutateAsync({id:'id',methodId:'card',targetBalance:'100',expectedBalance:'50.00',note:null})).rejects.toThrow('Refresh balances');});expect(h.invalidate).not.toHaveBeenCalled();h.unmount();h.client.clear();});
