do $$
declare debit budget_tracker.payment_methods; credit budget_tracker.payment_methods; cash budget_tracker.payment_methods;
 transfer_payload jsonb; correction_payload jsonb; rule_payload jsonb; tx_payload jsonb;
 f budget_tracker.payment_transfers; correction budget_tracker.balance_corrections; r budget_tracker.recurring_rules; t budget_tracker.transactions;
 today date:=(now() at time zone 'Asia/Manila')::date; original_baseline timestamptz; total_before numeric; raw numeric;
begin
 select * into debit from budget_tracker.payment_methods where name='Metrobank synthetic';
 select * into cash from budget_tracker.payment_methods where method='cash';
 credit:=budget_tracker.save_payment_method(jsonb_build_object('operation','create','id',gen_random_uuid(),'method','card','paymentType','Credit card','name','Independent credit','openingBalance','500.00'));
 original_baseline:=credit.baseline_at;
 tx_payload:=jsonb_build_object('payload_version',3,'note',null,'operation','create','id',gen_random_uuid(),'type','expense','category_id','00000000-0000-4000-8000-000000009903','amount','100.00','occurred_at',now(),'transaction_date',today,'payment_method_id',credit.id);
 t:=budget_tracker.save_transaction(tx_payload,'[]');
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'id'=credit.id::text;
 if raw<>-600 then raise exception 'Credit spending did not increase debt';end if;
 begin perform budget_tracker.save_payment_method(jsonb_build_object('operation','update','id',credit.id,'method','card','paymentType','Credit card','name','Independent credit','openingBalance','550.00'));raise exception 'Initial balance changed without confirmation';exception when invalid_parameter_value then null;end;
 credit:=budget_tracker.save_payment_method(jsonb_build_object('operation','update','id',credit.id,'method','card','paymentType','Credit card','name','Independent credit','openingBalance','550.00','confirmOpening',true));
 if credit.baseline_at<>original_baseline then raise exception 'Initial edit reset baseline';end if;
 select sum(amount) into total_before from budget_tracker.transactions;
 transfer_payload:=jsonb_build_object('operation','create','id',gen_random_uuid(),'sourceId',cash.id,'destinationId',credit.id,'amount','700.00','date',today,'note','Repayment');
 f:=budget_tracker.save_payment_transfer(transfer_payload);
 if (budget_tracker.save_payment_transfer(transfer_payload)).id<>f.id then raise exception 'Transfer exact retry failed';end if;
 begin perform budget_tracker.save_payment_transfer(transfer_payload||jsonb_build_object('amount','701.00'));raise exception 'Transfer conflicting retry accepted';exception when unique_violation then null;end;
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'id'=credit.id::text;
 if raw<>50 then raise exception 'Credit overpayment not positive credit balance';end if;
 if total_before<>(select sum(amount) from budget_tracker.transactions) then raise exception 'Transfer polluted budget totals';end if;
 perform budget_tracker.save_payment_transfer(transfer_payload||jsonb_build_object('operation','update','amount','650.00'));
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'id'=credit.id::text;
 if raw<>0 then raise exception 'Transfer edit did not replace contribution';end if;
 perform budget_tracker.save_payment_transfer(jsonb_build_object('id',f.id,'operation','delete'));
 perform budget_tracker.save_payment_transfer(jsonb_build_object('id',f.id,'operation','delete'));
 correction_payload:=jsonb_build_object('id',gen_random_uuid(),'methodId',credit.id,'targetBalance','400.00','expectedBalance','-650.00','note','Statement reconciliation');
 correction:=budget_tracker.correct_method_balance(correction_payload);
 if correction.delta<>250 then raise exception 'Correction delta incorrect';end if;
 if (budget_tracker.correct_method_balance(correction_payload)).id<>correction.id then raise exception 'Correction exact retry failed';end if;
 begin perform budget_tracker.correct_method_balance(correction_payload||jsonb_build_object('id',gen_random_uuid()));raise exception 'Stale correction accepted';exception when serialization_failure then null;end;
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'id'=credit.id::text;
 if raw<>-400 then raise exception 'Correction failed';end if;
 if total_before<>(select sum(amount) from budget_tracker.transactions) then raise exception 'Correction polluted budget totals';end if;
 rule_payload:=jsonb_build_object('categoryId','00000000-0000-4000-8000-000000009903','amount','25.00','frequency','monthly','nextDueDate',today,'note','Payment bill','paymentMethodId',debit.id);
 r:=budget_tracker.save_recurring_rule(rule_payload);
 perform budget_tracker.prepare_dashboard(date_trunc('month',today)::date);
 if not exists(select from budget_tracker.transactions where recurring_rule_id=r.id and payment_method_id=debit.id) then raise exception 'Bill catch-up lost method';end if;
 r:=budget_tracker.save_recurring_rule(rule_payload||jsonb_build_object('id',r.id,'nextDueDate',today+interval '1 month','paymentMethodId',credit.id));
 if not exists(select from budget_tracker.transactions where recurring_rule_id=r.id and payment_method_id=debit.id) then raise exception 'Bill update rewrote recorded history';end if;
 if exists(select from budget_tracker.recurring_occurrences where rule_id=r.id and state='outstanding' and scheduled_date>=today and payment_method_id is distinct from credit.id) then raise exception 'Future bill assignment not updated';end if;
 begin perform budget_tracker.save_payment_method(jsonb_build_object('id',credit.id,'operation','archive'));raise exception 'Archive allowed linked bill without reassignment';exception when invalid_parameter_value then null;end;
 perform budget_tracker.save_payment_method(jsonb_build_object('id',credit.id,'operation','archive','reassignBills',true,'replacementMethodId',debit.id));
 if exists(select from budget_tracker.recurring_rules where id=r.id and payment_method_id is distinct from debit.id) or exists(select from budget_tracker.recurring_occurrences where rule_id=r.id and state in ('outstanding','replacement') and payment_method_id is distinct from debit.id) then raise exception 'Archive did not atomically reassign bills';end if;
 -- Initialize the second owner's Cash after historical and future records exist.
 perform set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000009902',true);
 perform budget_tracker.payment_method_snapshot();select * into cash from budget_tracker.payment_methods where method='cash';
 t:=budget_tracker.save_transaction(jsonb_build_object('payload_version',3,'note',null,'operation','create','id',gen_random_uuid(),'type','expense','category_id','00000000-0000-4000-8000-000000009904','amount','100.00','occurred_at',now(),'transaction_date',today-1),'[]');
 cash:=budget_tracker.save_payment_method(jsonb_build_object('operation','update','id',cash.id,'method','cash','paymentType','Cash','name','Cash','openingBalance','1000.00'));
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'method'='cash';
 if raw<>1000 then raise exception 'Old Cash history deducted twice';end if;
 t:=budget_tracker.save_transaction(jsonb_build_object('payload_version',3,'note',null,'operation','update','id',t.id,'type','expense','category_id','00000000-0000-4000-8000-000000009904','amount','200.00','occurred_at',now(),'transaction_date',today-1),'[]');
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'method'='cash';
 if raw<>1000 then raise exception 'Ordinary edit reset assignment timestamp';end if;
 perform budget_tracker.save_transaction(jsonb_build_object('payload_version',3,'note',null,'operation','create','id',gen_random_uuid(),'type','expense','category_id','00000000-0000-4000-8000-000000009904','amount','50.00','occurred_at',now(),'transaction_date',today-3),'[]');
 select (b->>'balance')::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') b where b->>'method'='cash';
 if raw<>950 then raise exception 'New backdated Cash receipt excluded';end if;
end $$;
