do $$
declare
 method_cash CONSTANT text := 'cash';
 key_operation CONSTANT text := 'operation';
 operation_create CONSTANT text := 'create';
 key_id CONSTANT text := 'id';
 key_method CONSTANT text := 'method';
 method_card CONSTANT text := 'card';
 key_payment_type CONSTANT text := 'paymentType';
 credit_card_type CONSTANT text := 'Credit card';
 key_name CONSTANT text := 'name';
 credit_name CONSTANT text := 'Independent credit';
 key_opening_balance CONSTANT text := 'openingBalance';
 key_payload_version CONSTANT text := 'payload_version';
 key_note CONSTANT text := 'note';
 key_type CONSTANT text := 'type';
 expense_type CONSTANT text := 'expense';
 key_category_id CONSTANT text := 'category_id';
 key_amount CONSTANT text := 'amount';
 key_occurred_at CONSTANT text := 'occurred_at';
 key_transaction_date CONSTANT text := 'transaction_date';
 empty_items CONSTANT jsonb := '[]';
 key_balance CONSTANT text := 'balance';
 key_methods CONSTANT text := 'methods';
 operation_update CONSTANT text := 'update';
 other_category CONSTANT text := '00000000-0000-4000-8000-000000009904';
 debit budget_tracker.payment_methods; credit budget_tracker.payment_methods; cash budget_tracker.payment_methods;
 transfer_payload jsonb; correction_payload jsonb; rule_payload jsonb; tx_payload jsonb;
 f budget_tracker.payment_transfers; correction budget_tracker.balance_corrections; r budget_tracker.recurring_rules; t budget_tracker.transactions;
 today date:=(now() at time zone 'Asia/Manila')::date; original_baseline timestamptz; total_before numeric; raw numeric;
begin
 select * into debit from budget_tracker.payment_methods where name='Metrobank synthetic';
 select * into cash from budget_tracker.payment_methods where method=method_cash;
 credit:=budget_tracker.save_payment_method(jsonb_build_object(key_operation,operation_create,key_id,gen_random_uuid(),key_method,method_card,key_payment_type,credit_card_type,key_name,credit_name,key_opening_balance,'500.00'));
 original_baseline:=credit.baseline_at;
 tx_payload:=jsonb_build_object(key_payload_version,3,key_note,null,key_operation,operation_create,key_id,gen_random_uuid(),key_type,expense_type,key_category_id,'00000000-0000-4000-8000-000000009903',key_amount,'100.00',key_occurred_at,now(),key_transaction_date,today,'payment_method_id',credit.id);
 t:=budget_tracker.save_transaction(tx_payload,empty_items);
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_id=credit.id::text;
 if raw<>-600 then raise exception 'Credit spending did not increase debt';end if;
 begin perform budget_tracker.save_payment_method(jsonb_build_object(key_operation,operation_update,key_id,credit.id,key_method,method_card,key_payment_type,credit_card_type,key_name,credit_name,key_opening_balance,'550.00'));raise exception 'Initial balance changed without confirmation';exception when invalid_parameter_value then null;end;
 credit:=budget_tracker.save_payment_method(jsonb_build_object(key_operation,operation_update,key_id,credit.id,key_method,method_card,key_payment_type,credit_card_type,key_name,credit_name,key_opening_balance,'550.00','confirmOpening',true));
 if credit.baseline_at<>original_baseline then raise exception 'Initial edit reset baseline';end if;
 select sum(amount) into total_before from budget_tracker.transactions;
 transfer_payload:=jsonb_build_object(key_operation,operation_create,key_id,gen_random_uuid(),'sourceId',cash.id,'destinationId',credit.id,key_amount,'700.00','date',today,key_note,'Repayment');
 f:=budget_tracker.save_payment_transfer(transfer_payload);
 if (budget_tracker.save_payment_transfer(transfer_payload)).id<>f.id then raise exception 'Transfer exact retry failed';end if;
 begin perform budget_tracker.save_payment_transfer(transfer_payload||jsonb_build_object(key_amount,'701.00'));raise exception 'Transfer conflicting retry accepted';exception when unique_violation then null;end;
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_id=credit.id::text;
 if raw<>50 then raise exception 'Credit overpayment not positive credit balance';end if;
 if total_before<>(select sum(amount) from budget_tracker.transactions) then raise exception 'Transfer polluted budget totals';end if;
 perform budget_tracker.save_payment_transfer(transfer_payload||jsonb_build_object(key_operation,operation_update,key_amount,'650.00'));
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_id=credit.id::text;
 if raw<>0 then raise exception 'Transfer edit did not replace contribution';end if;
 perform budget_tracker.save_payment_transfer(jsonb_build_object(key_id,f.id,key_operation,'delete'));
 perform budget_tracker.save_payment_transfer(jsonb_build_object(key_id,f.id,key_operation,'delete'));
 correction_payload:=jsonb_build_object(key_id,gen_random_uuid(),'methodId',credit.id,'targetBalance','400.00','expectedBalance','-650.00',key_note,'Statement reconciliation');
 correction:=budget_tracker.correct_method_balance(correction_payload);
 if correction.delta<>250 then raise exception 'Correction delta incorrect';end if;
 if (budget_tracker.correct_method_balance(correction_payload)).id<>correction.id then raise exception 'Correction exact retry failed';end if;
 begin perform budget_tracker.correct_method_balance(correction_payload||jsonb_build_object(key_id,gen_random_uuid()));raise exception 'Stale correction accepted';exception when serialization_failure then null;end;
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_id=credit.id::text;
 if raw<>-400 then raise exception 'Correction failed';end if;
 if total_before<>(select sum(amount) from budget_tracker.transactions) then raise exception 'Correction polluted budget totals';end if;
 rule_payload:=jsonb_build_object('categoryId','00000000-0000-4000-8000-000000009903',key_amount,'25.00','frequency','monthly','nextDueDate',today,key_note,'Payment bill','paymentMethodId',debit.id);
 r:=budget_tracker.save_recurring_rule(rule_payload);
 perform budget_tracker.prepare_dashboard(date_trunc('month',today)::date);
 if not exists(select from budget_tracker.transactions where recurring_rule_id=r.id and payment_method_id=debit.id) then raise exception 'Bill catch-up lost method';end if;
 r:=budget_tracker.save_recurring_rule(rule_payload||jsonb_build_object(key_id,r.id,'nextDueDate',today+interval '1 month','paymentMethodId',credit.id));
 if not exists(select from budget_tracker.transactions where recurring_rule_id=r.id and payment_method_id=debit.id) then raise exception 'Bill update rewrote recorded history';end if;
 if exists(select from budget_tracker.recurring_occurrences where rule_id=r.id and state='outstanding' and scheduled_date>=today and payment_method_id is distinct from credit.id) then raise exception 'Future bill assignment not updated';end if;
 begin perform budget_tracker.save_payment_method(jsonb_build_object(key_id,credit.id,key_operation,'archive'));raise exception 'Archive allowed linked bill without reassignment';exception when invalid_parameter_value then null;end;
 perform budget_tracker.save_payment_method(jsonb_build_object(key_id,credit.id,key_operation,'archive','reassignBills',true,'replacementMethodId',debit.id));
 if exists(select from budget_tracker.recurring_rules where id=r.id and payment_method_id is distinct from debit.id) or exists(select from budget_tracker.recurring_occurrences where rule_id=r.id and state in ('outstanding','replacement') and payment_method_id is distinct from debit.id) then raise exception 'Archive did not atomically reassign bills';end if;
 -- Initialize the second owner's Cash after historical and future records exist.
 perform set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000009902',true);
 perform budget_tracker.payment_method_snapshot();select * into cash from budget_tracker.payment_methods where method=method_cash;
 t:=budget_tracker.save_transaction(jsonb_build_object(key_payload_version,3,key_note,null,key_operation,operation_create,key_id,gen_random_uuid(),key_type,expense_type,key_category_id,other_category,key_amount,'100.00',key_occurred_at,now(),key_transaction_date,today-1),empty_items);
 cash:=budget_tracker.save_payment_method(jsonb_build_object(key_operation,operation_update,key_id,cash.id,key_method,method_cash,key_payment_type,'Cash',key_name,'Cash',key_opening_balance,'1000.00'));
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_method=method_cash;
 if raw<>1000 then raise exception 'Old Cash history deducted twice';end if;
 t:=budget_tracker.save_transaction(jsonb_build_object(key_payload_version,3,key_note,null,key_operation,operation_update,key_id,t.id,key_type,expense_type,key_category_id,other_category,key_amount,'200.00',key_occurred_at,now(),key_transaction_date,today-1),empty_items);
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_method=method_cash;
 if raw<>1000 then raise exception 'Ordinary edit reset assignment timestamp';end if;
 perform budget_tracker.save_transaction(jsonb_build_object(key_payload_version,3,key_note,null,key_operation,operation_create,key_id,gen_random_uuid(),key_type,expense_type,key_category_id,other_category,key_amount,'50.00',key_occurred_at,now(),key_transaction_date,today-3),empty_items);
 select (b->>key_balance)::numeric into raw from jsonb_array_elements(budget_tracker.payment_method_snapshot()->key_methods) b where b->>key_method=method_cash;
 if raw<>950 then raise exception 'New backdated Cash receipt excluded';end if;
end $$;
