insert into auth.users(id) values('00000000-0000-4000-8000-000000009701'),('00000000-0000-4000-8000-000000009702');
insert into budget_tracker.profiles(user_id,timezone) values('00000000-0000-4000-8000-000000009701','UTC'),('00000000-0000-4000-8000-000000009702','UTC');
insert into budget_tracker.income_sources(id,user_id,name,creation_name) values('00000000-0000-4000-8000-000000009704','00000000-0000-4000-8000-000000009702','Foreign','Foreign');
set local request.jwt.claim.sub='00000000-0000-4000-8000-000000009701';
set local role authenticated;
do $cases$
declare
 source_id constant uuid:='00000000-0000-4000-8000-000000009703';
 foreign_source constant uuid:='00000000-0000-4000-8000-000000009704';
 tx_id constant uuid:='00000000-0000-4000-8000-000000009705';
 category uuid; month date:=date_trunc('month',now() at time zone 'UTC')::date;
 today date:=(now() at time zone 'UTC')::date;
 payload jsonb; snapshot jsonb; source budget_tracker.income_sources; saved budget_tracker.transactions; n integer;
 cash budget_tracker.payment_methods; bank budget_tracker.payment_methods; bank2 budget_tracker.payment_methods; history jsonb; occurrence uuid; previous_expense text; expected_balance text;
begin
 select id into category from budget_tracker.categories where user_id=auth.uid() and name='Groceries' limit 1;
 source:=budget_tracker.save_income_source(jsonb_build_object('operation','create','id',source_id,'name','Salary'));
 source:=budget_tracker.save_income_source(jsonb_build_object('operation','create','id',source_id,'name','Salary'));
 if (select count(*) from budget_tracker.income_sources where user_id=auth.uid())<>1 then raise exception 'Source retry duplicated';end if;
 begin perform budget_tracker.save_income_source(jsonb_build_object('operation','create','id',source_id,'name','Conflict'));raise exception 'Conflicting source accepted';exception when unique_violation then null;end;
 payload:=jsonb_build_object('operation','create','payload_version',4,'id',tx_id,'type','income','category_id',null,'amount','200.00','note','Synthetic income','occurred_at',month::timestamptz,'transaction_date',month,'income_source_id',source_id);
 saved:=budget_tracker.save_transaction(payload,'[]');
 if saved.income_source_id<>source_id then raise exception 'Source not assigned';end if;
 perform budget_tracker.save_income_source(jsonb_build_object('operation','archive','id',source_id));
 saved:=budget_tracker.save_transaction(payload,'[]');
 source:=budget_tracker.save_income_source(jsonb_build_object('operation','create','id',source_id,'name','Salary'));
 if not source.archived then raise exception 'Retry restored archived source';end if;
 saved:=budget_tracker.save_transaction((payload||jsonb_build_object('operation','update','payload_version',3,'note','Legacy edit'))-'income_source_id','[]');
 if saved.income_source_id<>source_id then raise exception 'Legacy edit erased source';end if;
 begin perform budget_tracker.save_transaction(payload||jsonb_build_object('id',gen_random_uuid()),'[]');raise exception 'Archived source accepted';exception when invalid_parameter_value then null;end;
 begin update budget_tracker.transactions set income_source_id=foreign_source where id=tx_id;raise exception 'Foreign direct assignment accepted';exception when insufficient_privilege then null;end;
 begin perform budget_tracker.save_transaction(payload||jsonb_build_object('id',gen_random_uuid(),'income_source_id',foreign_source),'[]');raise exception 'Foreign RPC assignment accepted';exception when insufficient_privilege then null;end;
 begin insert into budget_tracker.income_sources(id,user_id,name,creation_name) values(gen_random_uuid(),auth.uid(),'Direct','Direct');raise exception 'Direct source write accepted';exception when insufficient_privilege then null;end;
 saved:=budget_tracker.save_transaction(payload||jsonb_build_object('operation','update','type','expense','category_id',category,'amount','10.00'),'[]');
 if saved.income_source_id is not null then raise exception 'Expense retained source';end if;
 perform budget_tracker.save_income_source(jsonb_build_object('operation','restore','id',source_id));
 perform budget_tracker.save_transaction(payload||jsonb_build_object('id',gen_random_uuid()),'[]');
 perform budget_tracker.set_monthly_allowance(month,'5000.00');
 perform budget_tracker.set_category_budget(category,month,'500.00');
 insert into budget_tracker.transactions(id,user_id,type,category_id,amount,note,occurred_at,transaction_date)
 select gen_random_uuid(),auth.uid(),'expense',category,1,'Synthetic complete aggregate',month::timestamptz,month from generate_series(1,1001);
 insert into budget_tracker.transactions(id,user_id,type,category_id,amount,note,occurred_at,transaction_date) values(gen_random_uuid(),auth.uid(),'expense',category,90,'Synthetic previous', (month-interval '1 month')::timestamptz,(month-interval '1 month')::date);
 snapshot:=budget_tracker.reporting_snapshot(month);
 if snapshot->'totals'->>'expense'<>'101100' then raise exception 'Aggregate was truncated';end if;
 if snapshot->'totals'->>'income'<>'20000' then raise exception 'Income mismatch';end if;
 if jsonb_array_length(snapshot->'monthly')<>12 then raise exception 'Monthly range missing';end if;
 if jsonb_array_length(snapshot->'daily')<>extract(day from(month+interval '1 month - 1 day')) then raise exception 'Daily zero buckets missing';end if;
 if (select sum((value->>'amount')::numeric) from jsonb_array_elements(snapshot->'accounts'))<>101100 then raise exception 'Cash reconciliation failed';end if;
 if (select sum((value->>'spent')::numeric) from jsonb_array_elements(snapshot->'categories'))<>101100 then raise exception 'Category reconciliation failed';end if;
 if snapshot->'comparison'->'previous'->>'net'<>'-9000' then raise exception 'Previous negative net missing';end if;
 if today<(month+interval '1 month - 1 day')::date then
  insert into budget_tracker.transactions(id,user_id,type,category_id,amount,occurred_at,transaction_date) values(gen_random_uuid(),auth.uid(),'expense',category,7,(today+1)::timestamptz,today+1);
  snapshot:=budget_tracker.reporting_snapshot(month);
  if snapshot->'totals'->>'expense'<>'101800' or snapshot->'comparison'->'current'->>'expense'<>'101100' then raise exception 'MTD mixed with future entries';end if;
 end if;
 if budget_tracker.reporting_snapshot((month+interval '1 month')::date)->'comparison'<>'null'::jsonb then raise exception 'Future comparison present';end if;
 begin perform budget_tracker.reporting_snapshot((month+interval '25 months')::date);raise exception 'Unsupported month accepted';exception when invalid_parameter_value then null;end;
 if budget_tracker.report_cents(10000000000)<>'1000000000000' then raise exception 'Aggregate money capped';end if;
 history:=budget_tracker.report_transaction_history(month);
 if jsonb_array_length(history->'rows')<1003 then raise exception 'History truncated at 1000';end if;
 if (history->>'owner')::uuid<>auth.uid() or history->>'timezone'<>'UTC' then raise exception 'History context mismatch';end if;
 if (select sum((value->>'amount')::numeric) from jsonb_array_elements(history->'rows') where value->>'type'='expense')<>(snapshot->'totals'->>'expense')::numeric then raise exception 'History totals mismatch';end if;
 perform budget_tracker.payment_method_snapshot();select * into cash from budget_tracker.payment_methods where user_id=auth.uid() and method='cash';cash:=budget_tracker.save_payment_method(jsonb_build_object('operation','update','id',cash.id,'method','cash','name','Cash','paymentType','Cash','openingBalance','0.00'));
 bank:=budget_tracker.save_payment_method(jsonb_build_object('operation','create','id',gen_random_uuid(),'method','bank_account','paymentType','Bank account','name','Same bank','openingBalance','100.00'));
 bank2:=budget_tracker.save_payment_method(jsonb_build_object('operation','create','id',gen_random_uuid(),'method','bank_account','paymentType','Bank account','name','Same bank','openingBalance','100.00'));
 insert into budget_tracker.transactions(id,user_id,type,category_id,amount,occurred_at,transaction_date,payment_method_id) values(gen_random_uuid(),auth.uid(),'expense',null,2,month::timestamptz,month,cash.id),(gen_random_uuid(),auth.uid(),'expense',category,3,month::timestamptz,month,bank.id),(gen_random_uuid(),auth.uid(),'expense',category,4,month::timestamptz,month,bank2.id);
 for n in 1..1001 loop perform budget_tracker.save_payment_transfer(jsonb_build_object('id',gen_random_uuid(),'operation','create','sourceId',cash.id,'destinationId',bank.id,'amount','1.00','date',month,'note','Synthetic transfer'));end loop;
 snapshot:=budget_tracker.reporting_snapshot(month);
 if (select (value->>'amount')::numeric from jsonb_array_elements(snapshot->'accounts') where value->>'key'='cash')<101300 then raise exception 'Prebaseline or explicit Cash missing';end if;
 if (select count(*) from jsonb_array_elements(snapshot->'accounts') where value->>'name'='Same bank')<>2 then raise exception 'Duplicate banks merged';end if;
 if not exists(select from jsonb_array_elements(snapshot->'categories') where value->>'key'='uncategorized' and value->>'spent'='200') then raise exception 'Uncategorized missing';end if;
 if (select sum((value->>'amount')::numeric) from jsonb_array_elements(snapshot->'accounts'))<>(snapshot->'totals'->>'expense')::numeric then raise exception 'Accounts mismatch';end if;
 previous_expense:=snapshot->'totals'->>'expense';
 perform budget_tracker.save_payment_method(jsonb_build_object('id',bank.id,'operation','update','method','bank_account','paymentType','Bank account','name','Same bank','openingBalance','200.00','confirmOpening',true));
 select value->>'balance' into expected_balance from jsonb_array_elements(budget_tracker.payment_method_snapshot()->'methods') where value->>'id'=bank.id::text;
 perform budget_tracker.correct_method_balance(jsonb_build_object('id',gen_random_uuid(),'methodId',bank.id,'targetBalance','500.00','expectedBalance',expected_balance,'note','Synthetic correction'));
 perform budget_tracker.save_payment_method(jsonb_build_object('id',bank.id,'operation','archive'));
 snapshot:=budget_tracker.reporting_snapshot(month);
 if snapshot->'totals'->>'expense'<>previous_expense then raise exception 'Balance edits changed spending';end if;
 if not exists(select from jsonb_array_elements(snapshot->'accounts') where value->>'id'=bank.id::text and value->>'archived'='true' and value->>'amount'='300') then raise exception 'Archived account activity missing';end if;
 history:=budget_tracker.report_transfer_history(month);
 if jsonb_array_length(history->'rows')<>1001 then raise exception 'Transfer history truncated or double counted';end if;
 if history->'rows'->0->>'source_name'<>'Cash' or history->'rows'->0->>'destination_name'<>'Same bank' or history->'rows'->0->>'amount'<>'100' then raise exception 'Transfer detail mismatch';end if;
 -- Bill conversion uses the same successor save RPC, including source assignment.
 select id into occurrence from budget_tracker.recurring_occurrences where user_id=auth.uid() limit 1;
 if occurrence is null then
  perform budget_tracker.save_recurring_rule(jsonb_build_object('categoryId',category,'amount','5.00','note','Synthetic bill','frequency','monthly','nextDueDate',month));
  perform budget_tracker.prepare_dashboard(month);
  select id into occurrence from budget_tracker.recurring_occurrences where user_id=auth.uid() and state='recorded' limit 1;
 end if;
 perform budget_tracker.bill_command(occurrence,'convert_income',jsonb_build_object('payload_version',4,'amount','5.00','occurred_at',month::timestamptz,'transaction_date',month,'note','Converted income','income_source_id',source_id),'[]');
 if not exists(select from budget_tracker.transactions where user_id=auth.uid() and note='Converted income' and type='income' and income_source_id=source_id and occurrence_id is null) then raise exception 'Bill source conversion failed';end if;
 snapshot:=budget_tracker.reporting_snapshot(date '2024-02-01');
 if jsonb_array_length(snapshot->'daily')<>29 or jsonb_array_length(snapshot->'weekly')<>5 or snapshot->'comparison'->>'previousEnd'<>'2024-02-01' then raise exception 'Leap year or clipped weeks invalid';end if;
 insert into budget_tracker.transactions(id,user_id,type,category_id,amount,occurred_at,transaction_date) values(gen_random_uuid(),auth.uid(),'income',null,13,'2024-02-29T16:30:00Z',null);
 if budget_tracker.reporting_snapshot(date '2024-02-01')->'totals'->>'income'<>'1300' then raise exception 'UTC legacy boundary missing';end if;
 update budget_tracker.profiles set timezone='Asia/Manila' where user_id=auth.uid();
 if budget_tracker.reporting_snapshot(date '2024-02-01')->'totals'->>'income'<>'0' or budget_tracker.reporting_snapshot(date '2024-03-01')->'totals'->>'income'<>'1300' then raise exception 'Financial timezone boundary failed';end if;
 history:=budget_tracker.report_transaction_history(date '2024-03-01');
 if history->>'timezone'<>'Asia/Manila' or history->'rows'->0->>'financial_date'<>'2024-03-01' then raise exception 'History timezone boundary failed';end if;
 if has_function_privilege('anon','budget_tracker.report_transfer_history(date)','execute') or has_function_privilege('anon','budget_tracker.report_transaction_history(date)','execute') then raise exception 'Anonymous history execution allowed';end if;
 if has_function_privilege('anon','budget_tracker.reporting_snapshot(date)','execute') or has_function_privilege('anon','budget_tracker.save_income_source(jsonb)','execute') then raise exception 'Anonymous execution allowed';end if;
end $cases$;
reset role;
set constraints all immediate;
